name: test test test

on:
  workflow_call:

jobs:
  test-test-test-test-test-test-test-test:
    name: test test test test test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: see what we checked out
        run: |
          set -x
          env
          sleep 1
          git rev-parse HEAD
          sleep 1
          git describe --always --all
          sleep 1
          if [ -f README.md ]; then cat README.md; fi
          sleep 1
          cat "${GITHUB_EVENT_PATH}"
          

  runs-on-forks:
    name: this will run on everything including forks
    runs-on: ubuntu-latest

    steps:
      - run: echo "hello, forks"

  doesnt-run-on-forks:
    name: this will not run on PRs from forks
    runs-on: ubuntu-latest

    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}

    steps:
      - run: echo "hello, internal PR"